// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

sealed class PayPalWebCheckoutResultEvent {}

class PayPalWebCheckoutSuccessResultEvent extends PayPalWebCheckoutResultEvent {
  PayPalWebCheckoutSuccessResultEvent({this.orderId, this.payerId});

  String? orderId;

  String? payerId;

  List<Object?> _toList() {
    return <Object?>[orderId, payerId];
  }

  Object encode() {
    return _toList();
  }

  static PayPalWebCheckoutSuccessResultEvent decode(Object result) {
    result as List<Object?>;
    return PayPalWebCheckoutSuccessResultEvent(
      orderId: result[0] as String?,
      payerId: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PayPalWebCheckoutSuccessResultEvent ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PayPalWebCheckoutFailureResultEvent extends PayPalWebCheckoutResultEvent {
  PayPalWebCheckoutFailureResultEvent({
    this.orderId,
    required this.reason,
    required this.code,
    this.correlationId,
  });

  String? orderId;

  String reason;

  int code;

  String? correlationId;

  List<Object?> _toList() {
    return <Object?>[orderId, reason, code, correlationId];
  }

  Object encode() {
    return _toList();
  }

  static PayPalWebCheckoutFailureResultEvent decode(Object result) {
    result as List<Object?>;
    return PayPalWebCheckoutFailureResultEvent(
      orderId: result[0] as String?,
      reason: result[1]! as String,
      code: result[2]! as int,
      correlationId: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PayPalWebCheckoutFailureResultEvent ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PayPalWebCheckoutCanceledResultEvent
    extends PayPalWebCheckoutResultEvent {
  PayPalWebCheckoutCanceledResultEvent({this.orderId});

  String? orderId;

  List<Object?> _toList() {
    return <Object?>[orderId];
  }

  Object encode() {
    return _toList();
  }

  static PayPalWebCheckoutCanceledResultEvent decode(Object result) {
    result as List<Object?>;
    return PayPalWebCheckoutCanceledResultEvent(orderId: result[0] as String?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PayPalWebCheckoutCanceledResultEvent ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PayPalWebCheckoutErrorResultEvent extends PayPalWebCheckoutResultEvent {
  PayPalWebCheckoutErrorResultEvent({this.error});

  String? error;

  List<Object?> _toList() {
    return <Object?>[error];
  }

  Object encode() {
    return _toList();
  }

  static PayPalWebCheckoutErrorResultEvent decode(Object result) {
    result as List<Object?>;
    return PayPalWebCheckoutErrorResultEvent(error: result[0] as String?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PayPalWebCheckoutErrorResultEvent ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PayPalWebCheckoutSuccessResultEvent) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PayPalWebCheckoutFailureResultEvent) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PayPalWebCheckoutCanceledResultEvent) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PayPalWebCheckoutErrorResultEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return PayPalWebCheckoutSuccessResultEvent.decode(readValue(buffer)!);
      case 130:
        return PayPalWebCheckoutFailureResultEvent.decode(readValue(buffer)!);
      case 131:
        return PayPalWebCheckoutCanceledResultEvent.decode(readValue(buffer)!);
      case 132:
        return PayPalWebCheckoutErrorResultEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class PaypalPaymentHostApi {
  /// Constructor for [PaypalPaymentHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PaypalPaymentHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(String clientId, String environment) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.paypal_payment.PaypalPaymentHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[clientId, environment],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

class PayPalPaymentWebCheckoutHostApi {
  /// Constructor for [PayPalPaymentWebCheckoutHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PayPalPaymentWebCheckoutHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> startCheckout(String orderId, String fundingSource) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.paypal_payment.PayPalPaymentWebCheckoutHostApi.startCheckout$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[orderId, fundingSource],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

Stream<PayPalWebCheckoutResultEvent> payPalWebCheckoutResultEvent({
  String instanceName = '',
}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel payPalWebCheckoutResultEventChannel = EventChannel(
    'dev.flutter.pigeon.paypal_payment.PayPalWebCheckoutResultEventChannelApi.payPalWebCheckoutResultEvent$instanceName',
    pigeonMethodCodec,
  );
  return payPalWebCheckoutResultEventChannel.receiveBroadcastStream().map((
    dynamic event,
  ) {
    return event as PayPalWebCheckoutResultEvent;
  });
}
