// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonGeneratedPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class PayPalWebCheckoutResultEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class PayPalWebCheckoutSuccessResultEvent (
  val orderId: String? = null,
  val payerId: String? = null
) : PayPalWebCheckoutResultEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PayPalWebCheckoutSuccessResultEvent {
      val orderId = pigeonVar_list[0] as String?
      val payerId = pigeonVar_list[1] as String?
      return PayPalWebCheckoutSuccessResultEvent(orderId, payerId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      orderId,
      payerId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PayPalWebCheckoutSuccessResultEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PayPalWebCheckoutFailureResultEvent (
  val orderId: String? = null,
  val reason: String,
  val code: Long,
  val correlationId: String? = null
) : PayPalWebCheckoutResultEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PayPalWebCheckoutFailureResultEvent {
      val orderId = pigeonVar_list[0] as String?
      val reason = pigeonVar_list[1] as String
      val code = pigeonVar_list[2] as Long
      val correlationId = pigeonVar_list[3] as String?
      return PayPalWebCheckoutFailureResultEvent(orderId, reason, code, correlationId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      orderId,
      reason,
      code,
      correlationId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PayPalWebCheckoutFailureResultEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PayPalWebCheckoutCanceledResultEvent (
  val orderId: String? = null
) : PayPalWebCheckoutResultEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PayPalWebCheckoutCanceledResultEvent {
      val orderId = pigeonVar_list[0] as String?
      return PayPalWebCheckoutCanceledResultEvent(orderId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      orderId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PayPalWebCheckoutCanceledResultEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PayPalWebCheckoutErrorResultEvent (
  val error: String? = null
) : PayPalWebCheckoutResultEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PayPalWebCheckoutErrorResultEvent {
      val error = pigeonVar_list[0] as String?
      return PayPalWebCheckoutErrorResultEvent(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PayPalWebCheckoutErrorResultEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonGeneratedPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PayPalWebCheckoutSuccessResultEvent.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PayPalWebCheckoutFailureResultEvent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PayPalWebCheckoutCanceledResultEvent.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PayPalWebCheckoutErrorResultEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PayPalWebCheckoutSuccessResultEvent -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PayPalWebCheckoutFailureResultEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PayPalWebCheckoutCanceledResultEvent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PayPalWebCheckoutErrorResultEvent -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val PigeonGeneratedPigeonMethodCodec = StandardMethodCodec(PigeonGeneratedPigeonCodec())

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PaypalPaymentHostApi {
  fun initialize(clientId: String, environment: String)

  companion object {
    /** The codec used by PaypalPaymentHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonGeneratedPigeonCodec()
    }
    /** Sets up an instance of `PaypalPaymentHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PaypalPaymentHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.paypal_payment.PaypalPaymentHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as String
            val environmentArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.initialize(clientIdArg, environmentArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PayPalPaymentWebCheckoutHostApi {
  fun startCheckout(orderId: String, fundingSource: String)

  companion object {
    /** The codec used by PayPalPaymentWebCheckoutHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonGeneratedPigeonCodec()
    }
    /** Sets up an instance of `PayPalPaymentWebCheckoutHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PayPalPaymentWebCheckoutHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.paypal_payment.PayPalPaymentWebCheckoutHostApi.startCheckout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val orderIdArg = args[0] as String
            val fundingSourceArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.startCheckout(orderIdArg, fundingSourceArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class PigeonGeneratedPigeonStreamHandler<T>(
    val wrapper: PigeonGeneratedPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface PigeonGeneratedPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class PayPalWebCheckoutResultEventStreamHandler : PigeonGeneratedPigeonEventChannelWrapper<PayPalWebCheckoutResultEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: PayPalWebCheckoutResultEventStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.paypal_payment.PayPalWebCheckoutResultEventChannelApi.payPalWebCheckoutResultEvent"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = PigeonGeneratedPigeonStreamHandler<PayPalWebCheckoutResultEvent>(streamHandler)
      EventChannel(messenger, channelName, PigeonGeneratedPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
