// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeonGenerated(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeonGenerated(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeonGenerated(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeonGenerated(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeonGenerated(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeonGenerated(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol PayPalWebCheckoutResultEvent {

}

/// Generated class from Pigeon that represents data sent in messages.
struct PayPalWebCheckoutSuccessResultEvent: PayPalWebCheckoutResultEvent {
  var orderId: String? = nil
  var payerId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PayPalWebCheckoutSuccessResultEvent? {
    let orderId: String? = nilOrValue(pigeonVar_list[0])
    let payerId: String? = nilOrValue(pigeonVar_list[1])

    return PayPalWebCheckoutSuccessResultEvent(
      orderId: orderId,
      payerId: payerId
    )
  }
  func toList() -> [Any?] {
    return [
      orderId,
      payerId,
    ]
  }
  static func == (lhs: PayPalWebCheckoutSuccessResultEvent, rhs: PayPalWebCheckoutSuccessResultEvent) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PayPalWebCheckoutFailureResultEvent: PayPalWebCheckoutResultEvent {
  var orderId: String? = nil
  var reason: String
  var code: Int64
  var correlationId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PayPalWebCheckoutFailureResultEvent? {
    let orderId: String? = nilOrValue(pigeonVar_list[0])
    let reason = pigeonVar_list[1] as! String
    let code = pigeonVar_list[2] as! Int64
    let correlationId: String? = nilOrValue(pigeonVar_list[3])

    return PayPalWebCheckoutFailureResultEvent(
      orderId: orderId,
      reason: reason,
      code: code,
      correlationId: correlationId
    )
  }
  func toList() -> [Any?] {
    return [
      orderId,
      reason,
      code,
      correlationId,
    ]
  }
  static func == (lhs: PayPalWebCheckoutFailureResultEvent, rhs: PayPalWebCheckoutFailureResultEvent) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PayPalWebCheckoutCanceledResultEvent: PayPalWebCheckoutResultEvent {
  var orderId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PayPalWebCheckoutCanceledResultEvent? {
    let orderId: String? = nilOrValue(pigeonVar_list[0])

    return PayPalWebCheckoutCanceledResultEvent(
      orderId: orderId
    )
  }
  func toList() -> [Any?] {
    return [
      orderId
    ]
  }
  static func == (lhs: PayPalWebCheckoutCanceledResultEvent, rhs: PayPalWebCheckoutCanceledResultEvent) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PayPalWebCheckoutErrorResultEvent: PayPalWebCheckoutResultEvent {
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PayPalWebCheckoutErrorResultEvent? {
    let error: String? = nilOrValue(pigeonVar_list[0])

    return PayPalWebCheckoutErrorResultEvent(
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      error
    ]
  }
  static func == (lhs: PayPalWebCheckoutErrorResultEvent, rhs: PayPalWebCheckoutErrorResultEvent) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

private class PigeonGeneratedPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PayPalWebCheckoutSuccessResultEvent.fromList(self.readValue() as! [Any?])
    case 130:
      return PayPalWebCheckoutFailureResultEvent.fromList(self.readValue() as! [Any?])
    case 131:
      return PayPalWebCheckoutCanceledResultEvent.fromList(self.readValue() as! [Any?])
    case 132:
      return PayPalWebCheckoutErrorResultEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonGeneratedPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PayPalWebCheckoutSuccessResultEvent {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PayPalWebCheckoutFailureResultEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PayPalWebCheckoutCanceledResultEvent {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PayPalWebCheckoutErrorResultEvent {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonGeneratedPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonGeneratedPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonGeneratedPigeonCodecWriter(data: data)
  }
}

class PigeonGeneratedPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonGeneratedPigeonCodec(readerWriter: PigeonGeneratedPigeonCodecReaderWriter())
}

var pigeonGeneratedPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: PigeonGeneratedPigeonCodecReaderWriter());

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PaypalPaymentHostApi {
  func initialize(clientId: String, environment: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PaypalPaymentHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonGeneratedPigeonCodec.shared }
  /// Sets up an instance of `PaypalPaymentHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PaypalPaymentHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.paypal_payment_flutter.PaypalPaymentHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! String
        let environmentArg = args[1] as! String
        do {
          try api.initialize(clientId: clientIdArg, environment: environmentArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PayPalPaymentWebCheckoutHostApi {
  func startCheckout(orderId: String, fundingSource: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PayPalPaymentWebCheckoutHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonGeneratedPigeonCodec.shared }
  /// Sets up an instance of `PayPalPaymentWebCheckoutHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PayPalPaymentWebCheckoutHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startCheckoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.paypal_payment_flutter.PayPalPaymentWebCheckoutHostApi.startCheckout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startCheckoutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let orderIdArg = args[0] as! String
        let fundingSourceArg = args[1] as! String
        do {
          try api.startCheckout(orderId: orderIdArg, fundingSource: fundingSourceArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startCheckoutChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class PayPalWebCheckoutResultEventStreamHandler: PigeonEventChannelWrapper<PayPalWebCheckoutResultEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: PayPalWebCheckoutResultEventStreamHandler) {
    var channelName = "dev.flutter.pigeon.paypal_payment_flutter.PayPalWebCheckoutResultEventChannelApi.payPalWebCheckoutResultEvent"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<PayPalWebCheckoutResultEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: pigeonGeneratedPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
